# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This contains the postgres config settings provided to the startup command
# as "postgres -c config_file=<this file>".
#
# See https://github.com/postgres/postgres/blob/master/src/backend/utils/misc/postgresql.conf.sample
# for more config options.

# Conexões
listen_addresses = '*'
max_connections = 100

# Memória (Ajuste conforme a sua máquina, aqui assumo ~8GB de RAM disponíveis)
shared_buffers = 1GB              # Aumenta o cache do banco (requer um bom shm_size)
work_mem = 256MB                   # Crucial para DW e PostGIS: memória para ordenação e JOINs espaciais
maintenance_work_mem = 512MB      # Acelera a criação de índices espaciais (GIST) e VACUUM

# Paralelismo (Essencial para DW)
max_worker_processes = 4          # Número máximo de processos paralelos
max_parallel_workers_per_gather = 6 # Quantos workers podem atuar em uma única query
max_parallel_workers = 4

# Otimização do Planejador para Data Warehouse
random_page_cost = 1.1            # Se usar SSD (o padrão é 4.0, feito para HDDs antigos)