server:
  bind:
    host: 0.0.0.0
    port: 80
  url: http://localhost:5000
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false

logging:
  level: INFO

resources:
  car_area_imovel:
    type: collection
    title: CAR - Área do Imóvel
    description: Coleção do Cadastro Ambiental Rural
    keywords:
      - car
      - bdgeo
      - postgis
    links:
      - type: text/html
        rel: canonical
        title: Página da coleção
        href: http://localhost:5000/collections/car_area_imovel
        hreflang: pt-BR
    crs:
      - http://www.opengis.net/def/crs/OGC/1.3/CRS84h
      - EPSG:4674
    provider:
      type: feature
      name: PostgreSQL
      data:
        host: postgres_bdgeo
        port: 5432
        dbname: bdgeo_2026
        user: super_user
        password: super_password
      table: analytics.car_area_imovel
      geom:
        name: geom
        srid: 4674
      id_field: cod_imovel
      properties:
        - cod_imovel
        - id
        - status_imovel
        - dat_criacao
        - area
        - condicao
        - uf
        - municipio
        - cod_municipio_ibge
        - m_fiscal
        - tipo_imovel